"""
Verify Scenic files generated by retrieve/retrieve.py in the main chatscene environment.

The retrieval pipeline can run in a separate Python environment (e.g. Python 3.10 with
a modern PyTorch build for RTX 50-series GPUs), but Scenic compile-time verification
needs the full safebench/CARLA stack. This script is intended to be run from the main
chatscene (Python 3.8 + CARLA 0.9.13) environment.

Usage:
    conda activate chatscene
    python scripts/verify_dynamic_scenarios.py --port_ip 2000
"""
import os
import os.path as osp
import argparse
import shutil
import glob

from safebench.util.scenic_utils import ScenicSimulator


def main():
    parser = argparse.ArgumentParser(description="Verify generated dynamic Scenic files.")
    parser.add_argument('--port_ip', type=int, default=2000, help='CARLA port (default: 2000)')
    parser.add_argument('--scenic_dir', type=str, default='safebench/scenario/scenario_data/scenic_data/dynamic_scenario',
                        help='Directory containing generated .scenic files')
    args = parser.parse_args()

    root_dir = osp.abspath(osp.dirname(osp.dirname(osp.realpath(__file__))))
    scenic_dir = osp.join(root_dir, args.scenic_dir)
    scenic_files = sorted(glob.glob(osp.join(scenic_dir, 'dynamic_*.scenic')))

    if not scenic_files:
        print(f"No .scenic files found in {scenic_dir}")
        return

    extra_params = {'port': args.port_ip, 'traffic_manager_port': args.port_ip + 6000}
    passed = []
    failed = []

    for scenic_file in scenic_files:
        print(f"\nVerifying: {scenic_file}")
        try:
            ScenicSimulator(scenic_file, extra_params)
            print(f"  -> OK")
            passed.append(scenic_file)
        except Exception as e:
            print(f"  -> FAILED: {e}")
            failed.append(scenic_file)
            backup_path = scenic_file.replace('.scenic', '.txt')
            shutil.move(scenic_file, backup_path)
            print(f"  -> Moved to {backup_path}")

    print(f"\n{'='*60}")
    print(f"Verification complete: {len(passed)} passed, {len(failed)} failed out of {len(scenic_files)}")
    if failed:
        print("Failed files were renamed from .scenic to .txt for inspection.")


if __name__ == '__main__':
    main()
